jobs:

- job: Android
  pool:
    vmImage: 'macOS 10.13'
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '8.x'
    displayName: 'Install Node.js'

  - script: yarn install
    displayName: 'yarn install'

  - script: yarn add jetifier
    displayName: 'jetifier install'

  - script: npx jetify
    displayName: 'npx jetify'

  - task: Gradle@2
    displayName: 'Building Android app (release)'
    inputs:
      workingDirectory: 'android/'
      gradleWrapperFile: 'android/gradlew'
      gradleOptions: '-Xmx3072m'
      publishJUnitResults: false
      tasks: 'assembleRelease'
      
  - task: CopyFiles@2
    displayName: 'Copying .apk files...'
    inputs:
      contents: '**/*.apk'
      targetFolder: '$(build.artifactStagingDirectory)'
  
  - task: PublishBuildArtifacts@1
    displayName: 'Archiving .apk'
    inputs:
      pathToPublish: '$(build.artifactStagingDirectory)/app/build/outputs/'
      artifactName: 'apk'
      artifactType: 'container'

