jobs:

- job: Android
  pool:
    vmImage: 'macOS 10.13'
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '8.x'
    displayName: 'Install Node.js'

  - script: yarn install
    displayName: 'yarn install'

  - script: yarn add jetifier
    displayName: 'jetifier install'

  - script: npx jetify
    displayName: 'npx jetify'

  - task: Gradle@2
    displayName: 'Building Android app (release)'
    inputs:
      workingDirectory: 'android/'
      gradleWrapperFile: 'android/gradlew'
      gradleOptions: '-Xmx3072m'
      publishJUnitResults: false
      tasks: 'assembleRelease'


  - task: CopyFiles@2
    displayName: 'Copying .apk files...'
    inputs:
      contents: '**/*.apk'
      targetFolder: '$(build.artifactStagingDirectory)'

  - task: PublishBuildArtifacts@1
    displayName: 'Archiving .apk...'
    inputs:
      pathToPublish: '$(build.artifactStagingDirectory)/android/app/build/outputs/apk/'
      artifactName: 'apk'
      artifactType: 'container'

  - task: AppCenterDistribute@3
    inputs:
      serverEndpoint: 'testing app center'
      appSlug: 'uadacid/tama'
      appFile: '$(build.artifactStagingDirectory)/android/app/build/outputs/apk/release/app-release.apk'
      symbolsOption: 'Android'
      releaseNotesOption: 'input'
      releaseNotesInput: 'asdasdsadasd'
      destinationType: 'groups'
      distributionGroupId: '526b747e22d661dddd429d2ba60452613360322f'

  
  